# code: language=ansible
---
- name: Verify
  hosts: all
  gather_facts: false
  # check_mode: true
  become: true
  tasks:
    ## テストの前処理
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto
    - name: Gather service facts
      ansible.builtin.service_facts:
    - name: Gather facts on listening ports
      community.general.listen_ports_facts:
        command: ss
    - name: Set assert variables
      ansible.builtin.set_fact:
        listen_tcp_posts: "{{ ansible_facts.tcp_listen | map(attribute='port') | unique | sort | list }}"
        listen_udp_posts: "{{ ansible_facts.udp_listen | map(attribute='port') | unique | sort | list }}"
    ## パッケージのテスト
    - name: Assert package
      ansible.builtin.assert:
        that:
          - ansible_facts.packages['opendkim'] is defined
          - ansible_facts.packages['opendkim-tools'] is defined
        fail_msg: "OpenDKIM packages are not installed"
        success_msg: "OpenDKIM packages are installed"
    ## ユーザーのテスト
    - name: Test user
      block:
        - name: Get user facts
          ansible.builtin.getent:
            database: passwd
            key: opendkim
        - name: Assert user
          ansible.builtin.assert:
            that:
              - getent_passwd['opendkim'] is defined
            fail_msg: "opendkim user does not exist"
            success_msg: "opendkim user exists"
    ## グループのテスト
    - name: Test group
      block:
        - name: Get group facts
          ansible.builtin.getent:
            database: group
            key: www-data
        - name: Assert group
          ansible.builtin.assert:
            that:
              - getent_group['www-data'] is defined
            fail_msg: "www-data group does not exist"
            success_msg: "www-data group exists"
    # ファイルのテスト
    - name: Test files
      block:
        - name: Check KeyTable setting
          ansible.builtin.stat:
            path: /etc/opendkim/KeyTable
          register: result
        - name: Assert file
          ansible.builtin.assert:
            that:
              - result.stat.exists
            fail_msg: "OpenDKIM KeyTable is missing"
            success_msg: "OpenDKIM KeyTable exists"
        - name: Check SigningTable setting
          ansible.builtin.stat:
            path: /etc/opendkim/SigningTable
          register: result
        - name: Assert file
          ansible.builtin.assert:
            that:
              - result.stat.exists
            fail_msg: "OpenDKIM SigningTable is missing"
            success_msg: "OpenDKIM SigningTable exists"
        - name: Check TrustedHosts setting
          ansible.builtin.stat:
            path: /etc/opendkim/TrustedHosts
          register: result
        - name: Assert file
          ansible.builtin.assert:
            that:
              - result.stat.exists
            fail_msg: "OpenDKIM TrustedHosts is missing"
            success_msg: "OpenDKIM TrustedHosts exists"
    ## サービスのテスト
    - name: Assert service
      ansible.builtin.assert:
        that:
          - ansible_facts.services['opendkim.service'] is defined
          - ansible_facts.services['opendkim.service']['state'] == 'running'
          - ansible_facts.services['opendkim.service']['status'] == 'enabled'
        fail_msg: "opendkim service is not running or not enabled"
        success_msg: "opendkim service is running and enabled"
    ## ポートのテスト
    - name: Assert port
      ansible.builtin.assert:
        that:
          - 8891 in listen_tcp_posts
        fail_msg: "OpenDKIM is not listening on port 8891"
        success_msg: "OpenDKIM is listening on port 8891"
    ## OpenDKIMとPostfixの連携確認
    - name: Find log
      ansible.builtin.shell:
        cmd: grep -P "OpenDKIM Filter v\d{1,}\.\d{1,2}.\d{1,} starting" /var/log/mail.log
      changed_when: grep_result.rc > 1
      register: grep_result
    - name: Assert Log
      ansible.builtin.assert:
        that:
          - grep_result.stdout_lines | length > 0
        fail_msg: "OpenDKIM startup log entry not found"
        success_msg: "OpenDKIM startup log entry found"
    - name: Display DNS Configuration and Testing
      ansible.builtin.debug:
        msg: |
          See also
          https://wiki.debian.org/opendkim#DNS_Configuration
          https://wiki.debian.org/opendkim#Testing
